//! Prepare TLS connection and write server deploy bundle to data/ca/{slug}/.

use std::fs;
use std::path::PathBuf;

use anyhow::{Context, Result};

use crate::ca::{self, ServerCertBundle};

pub struct AgentDirInput<'a> {
    pub slug: &'a str,
    pub host: &'a str,
    pub port: u16,
    pub cert: &'a ServerCertBundle,
}

pub fn write_agent_dir(input: &AgentDirInput<'_>) -> Result<PathBuf> {
    let dir = ca::agent_dir(input.slug);
    let tls_dir = dir.join("tls");

    if dir.exists() {
        fs::remove_dir_all(&dir)
            .with_context(|| format!("Failed to refresh {}", dir.display()))?;
    }
    fs::create_dir_all(&tls_dir)?;

    let config_toml = format!(
        r#"# Generated by backup-client for connection "{slug}"
# device_id — empty until first client connects (auto-registered from client fingerprint)
device_id = ""
public_ip = "{host}"
server_port = {port}
server_addr = "0.0.0.0"
files_dir = "data/temp"
scripts_dir = "data/scripts"
debug = false
mysqldump_path = "mysqldump"
pg_dump_path = "pg_dump"
tls_cert = "tls/server.crt"
tls_key = "tls/server.key"
encrypt_backups = false
# Set encrypt_password before using Encrypt mode on tasks (same value in backup-decrypt).
encrypt_password = ""
"#,
        slug = input.slug,
        host = input.host,
        port = input.port,
    );

    fs::write(dir.join("config.toml"), config_toml)?;
    fs::write(tls_dir.join("server.crt"), &input.cert.server_cert_pem)?;
    fs::write(tls_dir.join("server.key"), &input.cert.server_key_pem)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(tls_dir.join("server.key"), fs::Permissions::from_mode(0o600))?;
    }

    let readme = format!(
        "Backup server files for connection \"{slug}\"\n\n\
         1. Copy this folder to the VPS (e.g. /opt/backup-server/)\n\
         2. Copy the backup-server Linux binary into the same folder\n\
         3. Install and start as a service:\n\n\
           cd /opt/backup-server\n\
           chmod +x backup-server service.sh\n\
           sudo ./service.sh\n\n\
         service.sh sets file ownership for the service user (SUDO_USER if you use sudo),\n\
         installs the systemd unit, and verifies \"Listening on https://\" in the journal.\n\n\
         Manual run (debug): ./backup-server\n\n\
         On first connect the client registers device_id automatically.\n\
         To allow a new PC: clear device_id in config.toml and restart backup-server.\n\n\
         WebSocket: wss://{host}:{port}/ws\n\
         Certificate fingerprint: {fp}\n\
         Valid for about {days} days.\n",
        slug = input.slug,
        host = input.host,
        port = input.port,
        fp = input.cert.fingerprint,
        days = input.cert.not_after_days,
    );
    fs::write(dir.join("README.txt"), readme)?;

    let service_sh = include_str!("../../server/service.sh");
    fs::write(dir.join("service.sh"), service_sh)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(dir.join("service.sh"), fs::Permissions::from_mode(0o755))?;
    }

    Ok(dir)
}

pub fn prepare_tls_connection(
    slug: &str,
    server_addr: &str,
) -> Result<(String, String, ca::ServerCertBundle, PathBuf)> {
    let host = ca::parse_host_from_server_addr(server_addr)?;
    let port = crate::ui::parse_server_addr(server_addr)?
        .rsplit_once(':')
        .and_then(|(_, p)| p.parse().ok())
        .unwrap_or(8080u16);

    let cert = ca::issue_server_cert(&host, slug)?;
    let agent_dir = write_agent_dir(&AgentDirInput {
        slug,
        host: &host,
        port,
        cert: &cert,
    })?;

    let url = crate::ui::wss_url_from_server_addr(server_addr)?;
    Ok((url, cert.fingerprint.clone(), cert, agent_dir))
}
